# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d657bedb62776afe0a616f9ec141e0ea1e98e6e545c7d46083efafd39f8919a0d9ed5a52b7a32750d85f304cd317a307e7f06da2f421d3e2d8203af5985874f

test:
  secret_key_base: b726c6f61ab72124ec10e31832518d3d7a383df45ea8a5bafce512a42cacfe96e57a18346440c01e7ed24fb5cbbbc3ce1ecc55aae6a4258eebec499a5a74d28a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
